AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Creation for EKS with public'

Parameters:
  EksClusterName:
    Description: Give Cluster Name for Creating Tags
    Type: String
    Default: "cluster-name"
  VpcCIDR:
    Description: Give Cluster Name for Creating Tags
    Type: String
    Default: "10.1.0.0/16"


Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref "VpcCIDR"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
        - Key: !Join ['/', ['kubernetes.io', 'cluster', !Ref "EksClusterName" ] ]
          Value: "shared"

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    DependsOn: VPC
    Properties:
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-IG" ]]
        - Key: !Join ['/', ['kubernetes.io', 'cluster', !Ref "EksClusterName" ] ]
          Value: "shared"

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-Public-RT" ]]

  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

## Start of Public Subnet Creation

  PublicSubNetAZ1:
    Type: 'AWS::EC2::Subnet'
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.1.0.0/22
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-public-",  !Select [ 0, !GetAZs '' ] ]]
        - Key: SubnetType
          Value: Public
        - Key: !Join ['/', ['kubernetes.io', 'cluster', !Ref "EksClusterName" ] ]
          Value: "shared"
        - Key: "kubernetes.io/role/elb"
          Value: "1"

  PublicSubnetAZ1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubNetAZ1
      RouteTableId: !Ref PublicRouteTable

  PublicSubNetAZ2:
    Type: 'AWS::EC2::Subnet'
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.1.4.0/22
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-public-",  !Select [ 1, !GetAZs '' ] ]]
        - Key: SubnetType
          Value: Public
        - Key: !Join ['/', ['kubernetes.io', 'cluster', !Ref "EksClusterName" ] ]
          Value: "shared"
        - Key: "kubernetes.io/role/elb"
          Value: "1"

  PublicSubnetAZ2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubNetAZ2
      RouteTableId: !Ref PublicRouteTable

  PublicSubNetAZ3:
    Type: 'AWS::EC2::Subnet'
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.1.8.0/22
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-public-",  !Select [ 2, !GetAZs '' ] ]]
        - Key: SubnetType
          Value: Public
        - Key: !Join ['/', ['kubernetes.io', 'cluster', !Ref "EksClusterName" ] ]
          Value: "shared"
        - Key: "kubernetes.io/role/elb"
          Value: "1"

  PublicSubnetAZ3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubNetAZ3
      RouteTableId: !Ref PublicRouteTable

